version: 'latest'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  dbclient:
    image: mongo
    ports:
      - 30000:27017
    volumes:
      - dbclient:/data/db
  dblivre:
    image: mongo
    ports:
      - 30001:27017
    volumes:
      - dblivre:/data/db
  dbemprunt:
    image: mongo
    ports:
      - 30002:27017
    volumes:
      - dbemprunt:/data/db
  dbnotification:
    image: mongo
    ports:
      - 30003:27017
    volumes:
      - dbnotification:/data/db
  clients:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - port=3000
      - url_mongoose=mongodb://dbclient:27017/dbclients
      - url_rabbit=amqp://guest:guest@rabbit:5672
      - secret=4e129721135ce7cbde0cd68bc4f7167e306367660f2ad3e14718c59ff9377308846905d0b136428da1e9dff9377308846905d0b136428daff9377308846905d0b136428da1e9d6085b56f73c
    depends_on:
      - rabbit
      - dbclient
  note:
    build: ./frontend
    ports:
      - 3001:3000
    environment:
      - port=3000
      - url_mongoose=mongodb://dbclient:27017/dbclients
      - url_rabbit=amqp://guest:guest@rabbit:5672
    depends_on:
      - rabbit
      - dbclient
volumes:
  dbclient:
  dblivre:
  dbemprunt:
  dbnotification: